### Prerequisites

* [ ] Are/were you student of CSE.CU ?
* [ ] Was this project graded ?
* [ ] Does this project have some licensing issues ?


### Details

0. [Project Name]
1. [Name]
2. [Student ID]
3. [Project REPO link]
4. [Some reference, to boost up verification speed]
5. [Current status as of today]
6. [If completed when did you completed this, else leave it blank]
7. [If graded put the course code here, else leave it blank]
8. [If it was group project put others name and ID else leave it blank]
9. [Any details you want to give]
10. [Duration]
11. [Technical specifications, write an essay if you want]
12. [Project reports, if you have any]
13. [Do you want further collaborations regarding it's development? If so, write as many as possible, else leave it blank]
